### ISSUE TITLE
What license is this released under?

### ISSUE THREAD

**Issue by BlueRaja** [Doublevil/JmdictFurigana#1]
Hey, awesome work on this project!  I was planning on doing this myself, I'm glad I searched around first.

However, I have one question - what license is this released under?  JMDict is released under [ShareAlike](https://creativecommons.org/licenses/by-sa/3.0/), though I'm not sure if this would be considered being "built upon the material"

**Comment by Doublevil** [comment]
Hey,

Thank you. That’s a good point. I’m not very familiar with licenses, so, given that JMDict is ShareAlike, let’s say my work is the same. The truth is, I don’t really care about your work using the same license at all. I don’t even mind if it’s commercial use. I just ask for proper credit.

I should really include a proper license to make this clear though.

Don’t hesitate if you want to talk about my projects, what you are working on, or any other Japanese resources.

Thank you for asking, and good luck with your project. :)

Doublevil

**Comment by BlueRaja** [comment]
The CC Share-Alike license requires derivative works to be under the same license.  But then according to [the KanjiDict license page](http://www.edrdg.org/edrdg/licence.html),

>  Software using these files does not have to be under any form of open-source license.

My totally-not-a-lawyer interpretation of this is that your [JmdictFurigana.txt](https://github.com/Doublevil/JmdictFurigana/releases/tag/1.0) file **must** be released under [CC Share-Alike](https://creativecommons.org/licenses/by-sa/3.0/), but the rest of the project can be released under whatever license you want.

Since it sounds like you don't want to make your work [copyleft](http://en.wikipedia.org/wiki/Copyleft) but _do_ want to require proper attribution, I would recommend releasing under [CC Attribution](https://creativecommons.org/licenses/by/4.0/).

Some developers _(due to stupid corporate policies or whatever)_ may not even be able to provide attribution, so I usually release [my projects](https://bitbucket.org/BlueRaja) under the [MIT license](http://opensource.org/licenses/MIT), which is basically _"Do whatever you want, no strings attached,"_ while still keeping you covered if someone uses your code in their nuclear reactor and the core melts or something.

Thanks for getting back to me so quickly, and for writing/open-sourcing this useful tool!

**Comment by fasiha** [comment]
It sounds like @Doublevil could have some wording in the project README saying "Same license as JMDict" and this would completely conform to his/her wishes. JMDict's awesome liberal license is possibly _the_ major reason it's so widely used and, especially given Doublevil's feelings above, this license is probably worth emulating for JmdictFurigana. My $0.02 :smiley:

**Comment by Doublevil** [comment]
Done, thanks. :)
