### ISSUE TITLE
New release coming? 

### ISSUE THREAD

**Issue by naomi789** [Doublevil/JmdictFurigana#10]
I was wondering if y'all are planning on a new release? https://github.com/Doublevil/JmdictFurigana/releases/tag/2.0

**Comment by Doublevil** [comment]
Hello,
I don't have anything planned on this project for now. If you just want a more up to date version, you can build the project, replace the dictionary file by a newer one, and run the console project and it will generate the file.

**Comment by fasiha** [comment]
@Doublevil sorry to ask this noob question, do you know how to "run the console project" on macOS? I installed .NET Core 3.1 SDK for macOS and while I was searching for things like "how to run SLN on mac" I thought maybe to ask you 😇 thank you!

(I noticed the JMDict XML is from 2016 and I need the fancy furigana breakdown for an entry that was added recently.)

**Comment by Doublevil** [comment]
@fasiha I'm still going to answer, but please don't jack old issues to ask unrelated questions.

> @Doublevil sorry to ask this noob question, do you know how to "run the console project" on macOS? I installed .NET Core 3.1

SDK for macOS and while I was searching for things like "how to run SLN on mac" I thought maybe to ask you 😇 thank you!
The project is .net framework 4.5, so it can't be run on macOS as is. You'll have to convert it to .net core or run it on a Windows machine.

> (I noticed the JMDict XML is from 2016 and I need the fancy furigana breakdown for an entry that was added recently.)

fwiw in the latest release I tried using the most recent JMDict XML file and it gave me the exact same number of entries.
