### ISSUE TITLE
compressed release files

### ISSUE THREAD

**Issue by MartinP7r** [Doublevil/JmdictFurigana#18]
Hi there! Thanks for setting this up! 

Would it be possible to have the github action also generate a compressed version (zip and/or tar) of the resulting json file?  This would reduce bandwidth usage quite a lot.

Best regards,
Martin

**Comment by MartinP7r** [comment]
@Doublevil let me ping you on this once again 🙏🏼

**Comment by Doublevil** [comment]
I've added both `.json.zip` and `.json.tar.gz` files to future releases, and also just generated a new release by running the action manually.

**Comment by MartinP7r** [comment]
That's great. Thanks so much!
