### ISSUE TITLE
Other forms

### ISSUE THREAD

**Issue by stephenmac7** [Doublevil/JmdictFurigana#2]
I'm using JmdictFurigana to create [a library](https://github.com/stephenmac7/jcore) which automatically associates text with readings, but it seems that sometimes, certain readings are not found. For example, [悪口](http://jisho.org/word/%E6%82%AA%E5%8F%A3) has multiple readings, but I can only find the main one-- あっこう. I don't think this is the intended behavior.

**Comment by Doublevil** [comment]
It seems that JMDict doesn't list 悪口　【わるくち】 nor 悪口　【わるぐち】; at least not in the version I used to generate the file.
Also, if your goal is to find the reading of a sentence or a full text, I think you'd better use a sentence processing tool -- my file is made only for static words on their own.

**Comment by Doublevil** [comment]
Oh wait, yes it is... my parsing must be off. I'll take a look at that asap.

**Comment by stephenmac7** [comment]
I am using a sentence processing tool to separate it into words that can go through your tool. As of now, it works pretty well, as shown in the [tests](https://github.com/stephenmac7/jcore/blob/master/src/test/scala/FuriganaTest.scala). So, thank you so much for your work and for looking into this.

**Comment by stephenmac7** [comment]
Any updates on this?

**Comment by Doublevil** [comment]
Sorry, I was planning to work on that a few weeks ago and then totally forgot about it. Thanks for your reminder ; I'm on it and you can expect it fixed this weekend.

**Comment by Doublevil** [comment]
Okay, it should be fixed now. Thank you very much, sorry for the wait, and don't hesitate to file another issue if you find something else. :)

**Comment by stephenmac7** [comment]
Thank you, it works perfectly!
