### ISSUE TITLE
Why does 明日 not have a line with あした?

### ISSUE THREAD

**Issue by fasiha** [Doublevil/JmdictFurigana#4]
This is most likely a user-is-a-huge-noob error, but I see only two entries for 明日:

```
明日|あす|0-1:あす
明日|みょうにち|0:みょう;1:にち
```

but none for the common reading あした, listed as first `reb` (reading) in JMDict. Any tips?

Also, many thanks for putting this together, it’s a monumental, and monumentally useful, effort 👌👍💓

**Comment by Doublevil** [comment]
Thanks for noticing this! It actually was a missing special reading in the file that lists these cases.

I just released 1.3, where I added everything on [this page](http://www16.atpages.jp/kanjikentei/jukujikun.html) to the list of special readings.
This should fix not only this issue, but probably lots of other missing readings (we now have like 3000-4000 more solved readings).
