### ISSUE TITLE
Entries containing the word "協会" (an example out of many!) have the wrong furiganas.

### ISSUE THREAD

**Issue by 2small2fall** [Doublevil/JmdictFurigana#6]
"協会" <-> "0-1:きょうかい"  --> CORRECT
"協会" <-> "0:きょう;1:かい" --> INCORRECT

**Comment by Doublevil** [comment]
Hello again yayoo1971,
This is actually not an error.
I'm currently rewriting part of the readme to explain the aim of the project in a better way. I'll commit my work asap.

**Comment by 2small2fall** [comment]
Alright, I'll check it.

Basically... I've done two sketches in the spirit of your README.

CORRECT
![2](https://cloud.githubusercontent.com/assets/3254992/20280878/934360dc-aaae-11e6-987f-18e197a8f3b9.jpg)

INCORRECT
![1](https://cloud.githubusercontent.com/assets/3254992/20280882/991b8296-aaae-11e6-81ab-a419d3f33475.jpg)

Difference is subtle but very important.

**Comment by BlueRaja** [comment]
Sorry, I am still a Japanese beginner, but.. why is the difference important?  Why would it be beneficial to consider a word as a special reading when it doesn't have to be?

**Comment by dgoedkoop** [comment]
The "correct" way makes it impossible to do searches, for example, for all
words containing 会 pronounced as かい.

Am 14.11.2016 9:14 nachm. schrieb "BlueRaja" notifications@github.com:

Sorry, I am still a Japanese beginner, but.. why is the difference
important? Why would it be beneficial to consider a word as a special
reading when it doesn't have to be?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/Doublevil/JmdictFurigana/issues/6#issuecomment-260448983,
or mute the thread

**Comment by Doublevil** [comment]
So basically what you explain is "wrong" is the whole aim of the project. I think JmdictFurigana is not the right resource for what you are trying to do.
I updated the readme, I hope my update makes it clearer what this project is and what it's not.
I'll keep the issue open for a while and close it when everyone agrees or when the discussion becomes unproductive.

**Comment by 2small2fall** [comment]
--> _The "correct" way makes it impossible to do searches, for example, for all
words containing 会 pronounced as かい._

Well, I don't get you as you can do such searches without jmdictfurigana in the first place.

会 
kunyomi : あ.う
onyomi : カイ, エ

For searching for a kanji, part of a word, based on its readings... it is quite straightforward with a simple sql table "words" with only these columns : 

kanji : 協会  
kana : きょうかい
kanjis_list : 協, 会

you get the readings via a query or simply by building a feature such as when clicking on the concerned kanji you get the reading + initiate a search (and can be even prompted if you want the search to be based on the "onyomi" or "kunyomi") to get all of the words containing it. 

-->
select \* from words where kanjis_list LIKE "%your_kanji%" AND kana LIKE "%your_reading%"
(or also, without the column kanjis_list : select \* from words where kanji LIKE "%your_kanji%" and kana LIKE "%your_reading%"

Anyway, Doublevil is right ; this is a non issue and it can be closed.
