### ISSUE TITLE
Special Expression Failure

### ISSUE THREAD

**Issue by DJTB** [Doublevil/JmdictFurigana#9]
Can you give an example of one of these failures?
> I am aware of an issue that incorrectly cuts certain special expressions because of the same-length algorithm. I consider these issues minor in number and importance.

Curious what exactly I should keep an eye out for.

This furigana list has been really helpful! 
Thanks for your work :100:

**Comment by Doublevil** [comment]
It's been a while, but if I remember correctly it happened for some entries written with letters or with numbers. Stuff like "ＤＡＴ 「ダット」" being cut in ダ, ッ and ト.
It probably doesn't affect a lot of more usual entries, especially since the update that added a large number of special readings.

**Comment by DJTB** [comment]
Roger, thanks for the info!
